#!/bin/bash

# Extract IPs and filter duplicates
mapfile lines < <(cat trace.txt  | grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | uniq)

# Header
echo 'graph {'

for ip in ${lines[*]}; do

	echo -e "\t\"$ip\""
done

# Footer
echo '}'
