#!/bin/bash

# Extract IPs and filter duplicates
mapfile lines < trace.txt

# Header
echo 'graph {'

ip+=("me")

# Extract IPs
for line in ${lines[*]}; do

	[[ $line =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]] && echo -n "\"${BASH_REMATCH[0]}\" -- " 

done

echo "end"

# Footer
echo '}'
