#!/bin/bash

# Extract IPs and filter duplicates
mapfile lines

# Header
echo 'graph {'

# Create array for IPs
IPs=()

# Extract IPs
for line in ${lines[*]}; do

	[[ $line =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]] && IPs+=("\"${BASH_REMATCH[0]}\"")
done

# For each pair of IPs create a connection
for (( i = 0; i < ${#IPs} - 1; ++i )); do

	now=${IPs[i]}
	next=${IPs[i + 1]}

	echo -e "\t$now -- $next"
done

# Footer
echo '}'
